server:
  port: 8006


spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 39.96.93.36
      port: 8500
      discovery:
        service-name: ${spring.application.name}